In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math
import sys
sys.path.append('../../')
from utils.Evaluation.calculate_metrics_tzo import calculate_scores
import seaborn as sns
from neo4j import GraphDatabase, basic_auth
sns.set_style(style='whitegrid')  # Better background

In [2]:
driver = GraphDatabase.driver('bolt://localhost:7687', auth=basic_auth('neo4j', 'moviesmovies') )
print(driver.verify_connectivity())

None

# Calculate Scores in dfs

Add the model name, the dataset and the path of results to calculate the scores

In [3]:
# SustainDataset
dataset = 'BenchmarkDataset2025'
model_name ='gpt_4o'
# path = f'../Outputs_Evaluation/{dataset}/{model_name}/{model_name}_tzo.xlsx'
path = f'../Outputs_Evaluation/{dataset}/{model_name}/{model_name}_eleftheria.xlsx'


# Read the model results
model_df = pd.read_excel(path)

# Calculate the scores
df = calculate_scores(model_name,dataset,model_df)

  0%|          | 0/2128 [00:00<?, ?it/s]

Skipping row 701, already computed.
Skipping row 702, already computed.
Skipping row 703, already computed.
Skipping row 704, already computed.
Skipping row 705, already computed.
Skipping row 706, already computed.
Skipping row 707, already computed.
Skipping row 708, already computed.
Skipping row 709, already computed.
Skipping row 710, already computed.
Skipping row 711, already computed.
Skipping row 712, already computed.
Skipping row 713, already computed.
Skipping row 714, already computed.
Skipping row 715, already computed.
Skipping row 716, already computed.
Skipping row 717, already computed.
Skipping row 718, already computed.
Skipping row 719, already computed.
Skipping row 720, already computed.
Skipping row 721, already computed.
Skipping row 722, already computed.
Skipping row 723, already computed.
Skipping row 724, already computed.
Skipping row 725, already computed.
Skipping row 726, already computed.
Skipping row 727, already computed.
Skipping row 728, already computed.
Skipping row 729, already computed.
Skipping row 730, already computed.
Skipping row 731, already computed.
Skipping row 732, already computed.
Skipping row 733, already computed.
Skipping row 734, already computed.
Skipping row 735, already computed.
Skipping row 736, already computed.
Skipping row 737, already computed.
Skipping row 738, already computed.
Skipping row 739, already computed.
Skipping row 740, already computed.
Skipping row 741, already computed.
Skipping row 742, already computed.
Skipping row 743, already computed.
Skipping row 744, already computed.
Skipping row 745, already computed.
Skipping row 746, already computed.
Skipping row 747, already computed.
Skipping row 748, already computed.
Skipping row 749, already computed.
Skipping row 750, already computed.
Skipping row 751, already computed.
Skipping row 752, already computed.
Skipping row 753, already computed.
Skipping row 754, already computed.
Skipping row 755, already computed.
Skipping row 756, already computed.
Skipping row 757, already computed.
Skipping row 758, already computed.
Skipping row 759, already computed.
Skipping row 760, already computed.
Skipping row 761, already computed.
Skipping row 762, already computed.
Skipping row 763, already computed.
Skipping row 764, already computed.
Skipping row 765, already computed.
Skipping row 766, already computed.
Skipping row 767, already computed.
Skipping row 768, already computed.
Skipping row 769, already computed.
Skipping row 770, already computed.
Skipping row 771, already computed.
Skipping row 772, already computed.
Skipping row 773, already computed.
Skipping row 774, already computed.
Skipping row 775, already computed.
Skipping row 776, already computed.
Skipping row 777, already computed.
Skipping row 778, already computed.
Skipping row 779, already computed.
Skipping row 780, already computed.
Skipping row 781, already computed.
Skipping row 782, already computed.
Skipping row 783, already computed.
Skipping row 784, already computed.
Skipping row 785, already computed.
Skipping row 786, already computed.
Skipping row 787, already computed.
Skipping row 788, already computed.
Skipping row 789, already computed.
Skipping row 790, already computed.
Skipping row 791, already computed.
Skipping row 792, already computed.
Skipping row 793, already computed.
Skipping row 794, already computed.
Skipping row 795, already computed.
Skipping row 796, already computed.
Skipping row 797, already computed.
Skipping row 798, already computed.
Skipping row 799, already computed.
Skipping row 800, already computed.
Skipping row 801, already computed.
Skipping row 802, already computed.
Skipping row 803, already computed.
Skipping row 804, already computed.
Skipping row 805, already computed.
Skipping row 806, already computed.
Skipping row 807, already computed.
Skipping row 808, already computed.
Skipping row 809, already computed.
Skipping row 810, already computed.
Skipping row 811, already computed.
Skipping row 812, already computed.
Skipping row 813, already computed.
Skipping row 814, already computed.
Skipping row 815, already computed.
Skipping row 816, already computed.
Skipping row 817, already computed.
Skipping row 818, already computed.
Skipping row 819, already computed.
Skipping row 820, already computed.
Skipping row 821, already computed.
Skipping row 822, already computed.
Skipping row 823, already computed.
Skipping row 824, already computed.
Skipping row 825, already computed.
Skipping row 826, already computed.
Skipping row 827, already computed.
Skipping row 828, already computed.
Skipping row 829, already computed.
Skipping row 830, already computed.
Skipping row 831, already computed.
Skipping row 832, already computed.
Skipping row 833, already computed.
Skipping row 834, already computed.
Skipping row 835, already computed.
Skipping row 836, already computed.
Skipping row 837, already computed.
Skipping row 838, already computed.
Skipping row 839, already computed.
Skipping row 840, already computed.
Skipping row 841, already computed.
Skipping row 842, already computed.
Skipping row 843, already computed.
Skipping row 844, already computed.
Skipping row 845, already computed.
Skipping row 846, already computed.
Skipping row 847, already computed.
Skipping row 848, already computed.
Skipping row 849, already computed.
Skipping row 850, already computed.
Skipping row 851, already computed.
Skipping row 852, already computed.
Skipping row 853, already computed.
Skipping row 854, already computed.
Skipping row 855, already computed.
Skipping row 856, already computed.
Skipping row 857, already computed.
Skipping row 858, already computed.
Skipping row 859, already computed.
Skipping row 860, already computed.
Skipping row 861, already computed.
Skipping row 862, already computed.
Skipping row 863, already computed.
Skipping row 864, already computed.
Skipping row 865, already computed.
Skipping row 866, already computed.
Skipping row 867, already computed.
Skipping row 868, already computed.
Skipping row 869, already computed.
Skipping row 870, already computed.
Skipping row 871, already computed.
Skipping row 872, already computed.
Skipping row 873, already computed.
Skipping row 874, already computed.
Skipping row 875, already computed.
Skipping row 876, already computed.
Skipping row 877, already computed.
Skipping row 878, already computed.
Skipping row 879, already computed.
Skipping row 880, already computed.
Skipping row 881, already computed.
Skipping row 882, already computed.
Skipping row 883, already computed.
Skipping row 884, already computed.
Skipping row 885, already computed.
Skipping row 886, already computed.
Skipping row 887, already computed.
Skipping row 888, already computed.
Skipping row 889, already computed.
Skipping row 890, already computed.
Skipping row 891, already computed.
Skipping row 892, already computed.
Skipping row 893, already computed.
Skipping row 894, already computed.
Skipping row 895, already computed.
Skipping row 896, already computed.
Skipping row 897, already computed.
Skipping row 898, already computed.
Skipping row 899, already computed.
Skipping row 900, already computed.
Skipping row 901, already computed.
Skipping row 902, already computed.
Skipping row 903, already computed.
Skipping row 904, already computed.
Skipping row 905, already computed.
Skipping row 906, already computed.
Skipping row 907, already computed.
Skipping row 908, already computed.
Skipping row 909, already computed.
Skipping row 910, already computed.
Skipping row 911, already computed.
Skipping row 912, already computed.
Skipping row 913, already computed.
Skipping row 914, already computed.
Skipping row 915, already computed.
Skipping row 916, already computed.
Skipping row 917, already computed.
Skipping row 918, already computed.
Skipping row 919, already computed.
Skipping row 920, already computed.
Skipping row 921, already computed.
Skipping row 922, already computed.
Skipping row 923, already computed.
Skipping row 924, already computed.
Skipping row 925, already computed.
Skipping row 926, already computed.
Skipping row 927, already computed.
Skipping row 928, already computed.
Skipping row 929, already computed.
Skipping row 930, already computed.
Skipping row 931, already computed.
Skipping row 932, already computed.
Skipping row 933, already computed.
Skipping row 934, already computed.
Skipping row 935, already computed.
Skipping row 936, already computed.
Skipping row 937, already computed.
Skipping row 938, already computed.
Skipping row 939, already computed.
Skipping row 940, already computed.
Skipping row 941, already computed.
Skipping row 942, already computed.
Skipping row 943, already computed.
Skipping row 944, already computed.
Skipping row 945, already computed.
Skipping row 946, already computed.
Skipping row 947, already computed.
Skipping row 948, already computed.
Skipping row 949, already computed.
Skipping row 950, already computed.
Skipping row 951, already computed.
Skipping row 952, already computed.
Skipping row 953, already computed.
Skipping row 954, already computed.
Skipping row 955, already computed.
Skipping row 956, already computed.
Skipping row 957, already computed.
Skipping row 958, already computed.
Skipping row 959, already computed.
Skipping row 960, already computed.
Skipping row 961, already computed.
Skipping row 962, already computed.
Skipping row 963, already computed.
Skipping row 964, already computed.
Skipping row 965, already computed.
Skipping row 966, already computed.
Skipping row 967, already computed.
Skipping row 968, already computed.
Skipping row 969, already computed.
Skipping row 970, already computed.
Skipping row 971, already computed.
Skipping row 972, already computed.
Skipping row 973, already computed.
Skipping row 974, already computed.
Skipping row 975, already computed.
Skipping row 976, already computed.
Skipping row 977, already computed.
Skipping row 978, already computed.
Skipping row 979, already computed.
Skipping row 980, already computed.
Skipping row 981, already computed.
Skipping row 982, already computed.
Skipping row 983, already computed.
Skipping row 984, already computed.
Skipping row 985, already computed.
Movies db locally

Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 43, offset: 42} for query: 'EXPLAIN MATCH (m:Movie) RETURN m.title, m.votes ORDER BY m.votes ASC LIMIT 3'

986 movies
Original Query: MATCH (m:Movie) RETURN m.title, m.votes ORDER BY m.votes ASC LIMIT 3
Generated Query:
MATCH (m:Movie)
RETURN m.title, m.votes
ORDER BY m.votes ASC
LIMIT 3

Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 42, offset: 41} for query: 'RETURN exists { MATCH (x:Movie) WHERE (x.votes) IS NOT NULL} AS exists'
c:\Users\ioann\Documents\ARSINOE Project\agentic-text-2-cypher\langgraph_workflow\Outputs_Evaluation\../..\utils\Evaluation\calculate_metrics_tzo.py:177: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[i, 'Original Syntax Valid'] = og_syntax_correct
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 2, column: 35, offset: 43} for query: 'EXPLAIN \nMATCH (m:Movie)\nRETURN m.title, m.votes\nORDER BY m.votes ASC\nLIMIT 3'
Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 42, offset: 41} for query: 'RETURN exists { MATCH (x:Movie) WHERE (x.votes) IS NOT NULL} AS exists'
c:\Users\ioann\Documents\ARSINOE Project\agentic-text-2-cypher\langgraph_workflow\Outputs_Evaluation\../..\utils\Evaluation\calculate_metrics_tzo.py:210: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[i, 'Syntax Valid'] = syntax_correct
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 35, offset: 34} for query: 'MATCH (m:Movie) RETURN m.title, m.votes ORDER BY m.votes ASC LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 2, column: 35, offset: 35} for query: '\nMATCH (m:Movie)\nRETURN m.title, m.votes\nORDER BY m.votes ASC\nLIMIT 3'
c:\Users\ioann\Documents\ARSINOE Project\agentic-text-2-cypher\langgraph_workflow\Outputs_Evaluation\../..\utils\Evaluation\calculate_metrics_tzo.py:253: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[i, 'Pass@1 Output'] = pass_1_output_result

Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 0.5
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 0.5
BLEU: 1.0
Rouge-L Precision: 1.0
Rouge-L Recall: 1.0
Rouge-L F1-score: 1.0
Jaro Similarity: 1
Jaccard Similarity: 1.0
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 987, already computed.
Skipping row 988, already computed.
Skipping row 989, already computed.
Skipping row 990, already computed.
Skipping row 991, already computed.
Movies db locally
992 movies
Original Query: MATCH (p:Person) WHERE p.born > 1980 AND (   (p)-[:ACTED_IN]->(:Movie) OR   (p)-[:DIRECTED]->(:Movie) OR   (p)-[:PRODUCED]->(:Movie) ) RETURN p
Generated Query:
MATCH (p:Person)-[r:ACTED_IN|DIRECTED|PRODUCED]->(m:Movie)
WHERE p.born > 1980
RETURN DISTINCT p.name, p.born, type(r) AS role, m.title
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.23768523881641235
Rouge-L Precision: 0.38
Rouge-L Recall: 0.45
Rouge-L F1-score: 0.42
Jaro Similarity: 0.8309807749280514
Jaccard Similarity: 0.36363636363636365
Jaccard Output: 0.4
Pass@1 Output: False
Skipping row 993, already computed.
Skipping row 994, already computed.
Skipping row 995, already computed.
Skipping row 996, already computed.
Movies db locally
997 movies
Original Query: MATCH (p:Person)-[:PRODUCED]->(m:Movie) WHERE exists {   (p)-[:DIRECTED]->(m) } AND exists {   (p)-[:WROTE]->(m) } RETURN p.name LIMIT 3
Generated Query:
MATCH (p1:Person)-[:PRODUCED]->(m:Movie)<-[:DIRECTED]-(p2:Person),
      (p3:Person)-[:WROTE]->(m)
WHERE p1 = p2 AND p2 = p3
RETURN p1.name
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.4995532102577887
Rouge-L Precision: 0.5
Rouge-L Recall: 0.57
Rouge-L F1-score: 0.53
Jaro Similarity: 0.8966023969560931
Jaccard Similarity: 0.6842105263157895
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 998, already computed.
Skipping row 999, already computed.
Skipping row 1000, already computed.
Skipping row 1001, already computed.
Skipping row 1002, already computed.
Skipping row 1003, already computed.
Skipping row 1004, already computed.
Skipping row 1005, already computed.
Skipping row 1006, already computed.
Movies db locally

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 43, offset: 42} for query: 'EXPLAIN MATCH (m:Movie) RETURN m.title, m.votes ORDER BY m.votes DESC LIMIT 1'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 42, offset: 41} for query: 'RETURN exists { MATCH (x:Movie) WHERE (x.votes) IS NOT NULL} AS exists'

1007 movies
Original Query: MATCH (m:Movie) RETURN m.title, m.votes ORDER BY m.votes DESC LIMIT 1
Generated Query:
MATCH (m:Movie)
RETURN m.title
ORDER BY m.votes DESC
LIMIT 1
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 0.5

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 4, column: 12, offset: 51} for query: 'EXPLAIN \nMATCH (m:Movie)\nRETURN m.title\nORDER BY m.votes DESC\nLIMIT 1'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 42, offset: 41} for query: 'RETURN exists { MATCH (x:Movie) WHERE (x.votes) IS NOT NULL} AS exists'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 35, offset: 34} for query: 'MATCH (m:Movie) RETURN m.title, m.votes ORDER BY m.votes DESC LIMIT 1'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 4, column: 12, offset: 43} for query: '\nMATCH (m:Movie)\nRETURN m.title\nORDER BY m.votes DESC\nLIMIT 1'

Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 0.5
BLEU: 0.7214103859635675
Rouge-L Precision: 1.0
Rouge-L Recall: 0.87
Rouge-L F1-score: 0.93
Jaro Similarity: 0.9288235294117647
Jaccard Similarity: 1.0
Jaccard Output: 0.5
Pass@1 Output: False
Skipping row 1008, already computed.
Skipping row 1009, already computed.
Skipping row 1010, already computed.
Skipping row 1011, already computed.
Skipping row 1012, already computed.
Skipping row 1013, already computed.
Skipping row 1014, already computed.
Skipping row 1015, already computed.
Skipping row 1016, already computed.
Skipping row 1017, already computed.
Skipping row 1018, already computed.
Skipping row 1019, already computed.
Skipping row 1020, already computed.
Skipping row 1021, already computed.
Movies db locally
1022 movies
Original Query: MATCH (p:Person)-[:DIRECTED]->(m:Movie) RETURN m.title, p.born ORDER BY p.born ASC LIMIT 1
Generated Query:
MATCH (p:Person)-[:DIRECTED]->(m:Movie)
RETURN m.title
ORDER BY p.born
LIMIT 1
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.7442627872450754
Rouge-L Precision: 1.0
Rouge-L Recall: 0.83
Rouge-L F1-score: 0.91
Jaro Similarity: 0.9484720176730486
Jaccard Similarity: 0.9285714285714286
Jaccard Output: 0.5
Pass@1 Output: False
Movies db locally
1023 movies
Original Query: MATCH (p:Person)-[:ACTED_IN]->(m:Movie) WHERE all(i IN range(2, toInteger(ceil(sqrt(m.released)))) WHERE m.released % i <> 0) RETURN DISTINCT p.name
Generated Query:
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
WHERE m.released IN [1975, 1977, 1979, 1987, 1993, 1997, 1999, 2003, 2007, 2011]
RETURN DISTINCT p.name
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.4370410372882731
Rouge-L Precision: 0.56
Rouge-L Recall: 0.52
Rouge-L F1-score: 0.54
Jaro Similarity: 0.8421172726707689
Jaccard Similarity: 0.3870967741935484
Jaccard Output: 0.9090909090909091
Pass@1 Output: False
Skipping row 1024, already computed.
Skipping row 1025, already computed.
Skipping row 1026, already computed.
Skipping row 1027, already computed.
Skipping row 1028, already computed.
Skipping row 1029, already computed.
Skipping row 1030, already computed.
Skipping row 1031, already computed.
Movies db locally
1032 movies
Original Query: MATCH (p:Person)-[r:REVIEWED]->(m:Movie) WHERE r.rating > 90 WITH p, count(m) AS moviesReviewed ORDER BY moviesReviewed DESC LIMIT 1 RETURN p.name AS reviewer, moviesReviewed
Generated Query: MATCH (p:Person)-[r:REVIEWED]->(m:Movie)
WHERE r.rating > 90
RETURN p.name, COUNT(m) AS reviewCount
ORDER BY reviewCount DESC
LIMIT 1
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.6449528865464121
Rouge-L Precision: 0.83
Rouge-L Recall: 0.69
Rouge-L F1-score: 0.75
Jaro Similarity: 0.8952623589026224
Jaccard Similarity: 0.8260869565217391
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1033, already computed.
Skipping row 1034, already computed.
Movies db locally
1035 movies
Original Query: MATCH (m:Movie)<-[:DIRECTED]-(d:Person) MATCH (m)<-[:WROTE]-(w:Person) WHERE d = w RETURN m.title, d.name
Generated Query:
MATCH (p:Person)-[:DIRECTED]->(m:Movie)<-[:WROTE]-(p)
RETURN m.title, p.name
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.43286401923505446
Rouge-L Precision: 0.62
Rouge-L Recall: 0.42
Rouge-L F1-score: 0.5
Jaro Similarity: 0.859549843183076
Jaccard Similarity: 0.6428571428571429
Jaccard Output: 1.0
Pass@1 Output: True
Movies db locally
1036 movies
Original Query: MATCH (m:Movie)<-[:DIRECTED]-(p:Person) WHERE m.title CONTAINS 'Give' RETURN DISTINCT p.name
Generated Query:
MATCH (p:Person)-[:DIRECTED]->(m:Movie)
WHERE m.title CONTAINS "Give"
RETURN p.name, m.title
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.5057338148181262
Rouge-L Precision: 0.69
Rouge-L Recall: 0.73
Rouge-L F1-score: 0.71
Jaro Similarity: 0.9076187766714082
Jaccard Similarity: 0.7857142857142857
Jaccard Output: 0.5
Pass@1 Output: False
Skipping row 1037, already computed.
Skipping row 1038, already computed.
Skipping row 1039, already computed.
Skipping row 1040, already computed.
Skipping row 1041, already computed.
Skipping row 1042, already computed.
Skipping row 1043, already computed.
Movies db locally
1044 movies
Original Query: MATCH (p:Person)-[:ACTED_IN]->(m:Movie) WHERE m.released >= 1970 AND m.released < 1980 RETURN m.title AS movie, count(p) AS actor_count ORDER BY actor_count DESC LIMIT 1
Generated Query:
MATCH (m:Movie)<-[:ACTED_IN]-(p:Person)
WHERE m.released >= 1970 AND m.released < 1980
AND EXISTS { MATCH (:Person)-[:PRODUCED]->(m) }
RETURN m.title, COUNT(p) AS actorCount
ORDER BY actorCount DESC
LIMIT 1
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.5104916699182128
Rouge-L Precision: 0.65
Rouge-L Recall: 0.69
Rouge-L F1-score: 0.67
Jaro Similarity: 0.8969123347811873
Jaccard Similarity: 0.8076923076923077
Jaccard Output: 0.0
Pass@1 Output: False
Skipping row 1045, already computed.
Skipping row 1046, already computed.
Skipping row 1047, already computed.
Skipping row 1048, already computed.
Skipping row 1049, already computed.
Skipping row 1050, already computed.
Skipping row 1051, already computed.
Skipping row 1052, already computed.
Skipping row 1053, already computed.
Skipping row 1054, already computed.
Skipping row 1055, already computed.
Skipping row 1056, already computed.
Skipping row 1057, already computed.
Skipping row 1058, already computed.
Movies db locally
1059 movies
Original Query: MATCH (director:Person)-[:DIRECTED]->(movie:Movie)<-[:ACTED_IN]-(actor:Person) WHERE director.born / 10 = actor.born / 10 RETURN DISTINCT actor.name
Generated Query:
MATCH (actor:Person)-[:ACTED_IN]->(movie:Movie)<-[:DIRECTED]-(director:Person)
WHERE toInteger(actor.born / 10) = toInteger(director.born / 10)
RETURN DISTINCT actor.name, director.name, movie.title
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.590135659237051
Rouge-L Precision: 0.52
Rouge-L Recall: 0.67
Rouge-L F1-score: 0.58
Jaro Similarity: 0.8743158861340681
Jaccard Similarity: 0.8823529411764706
Jaccard Output: 0.14414414414414414
Pass@1 Output: False
Skipping row 1060, already computed.
Skipping row 1061, already computed.
Skipping row 1062, already computed.
Skipping row 1063, already computed.
Movies db locally
1064 movies
Original Query: MATCH (p:Person)-[r:REVIEWED]->(m:Movie) WHERE r.rating > 90 RETURN p.name
Generated Query:
MATCH (p:Person)-[r:REVIEWED]->(m:Movie)
WHERE r.rating > 90
RETURN p.name, m.title, r.rating
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.7678350582993735
Rouge-L Precision: 0.78
Rouge-L Recall: 1.0
Rouge-L F1-score: 0.88
Jaro Similarity: 0.9579831932773109
Jaccard Similarity: 0.9230769230769231
Jaccard Output: 0.3333333333333333
Pass@1 Output: False
Skipping row 1065, already computed.
Skipping row 1066, already computed.
Skipping row 1067, already computed.
Movies db locally
1068 movies
Original Query: MATCH (m:Movie) RETURN m.title, m.released ORDER BY m.released LIMIT 3
Generated Query:
MATCH (m:Movie)
RETURN m.title, m.released
ORDER BY m.released ASC
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.8867047947918724
Rouge-L Precision: 0.93
Rouge-L Recall: 1.0
Rouge-L F1-score: 0.97
Jaro Similarity: 0.9831808278867102
Jaccard Similarity: 0.9090909090909091
Jaccard Output: 1.0
Pass@1 Output: True
Movies db locally
1069 movies
Original Query: MATCH (p:Person)-[:ACTED_IN]->(m:Movie) WITH p, COUNT(m) AS movieCount RETURN p.name AS actor, movieCount ORDER BY movieCount DESC LIMIT 5
Generated Query:
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
RETURN p.name AS actor, COUNT(m) AS movie_count
ORDER BY movie_count DESC
LIMIT 5
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.7020112563483173
Rouge-L Precision: 0.71
Rouge-L Recall: 0.68
Rouge-L F1-score: 0.69
Jaro Similarity: 0.9117937334149826
Jaccard Similarity: 0.8421052631578947
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1070, already computed.
Skipping row 1071, already computed.
Skipping row 1072, already computed.
Skipping row 1073, already computed.
Skipping row 1074, already computed.
Skipping row 1075, already computed.
Skipping row 1076, already computed.
Movies db locally
1077 movies
Original Query: MATCH (director:Person)-[:DIRECTED]->(movie:Movie) WHERE movie.released > 2000 WITH director, count(movie) AS movieCount, collect(movie.title) AS movies ORDER BY movieCount DESC LIMIT 1 RETURN director.name AS directorName, movies
Generated Query:
MATCH (p:Person)-[:DIRECTED]->(m:Movie)
WHERE m.released > 2000
WITH p, count(m) AS movieCount, collect(m.title) AS movies
ORDER BY movieCount DESC
LIMIT 1
RETURN p.name AS director, movies
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.6180487254346938
Rouge-L Precision: 0.76
Rouge-L Recall: 0.76
Rouge-L F1-score: 0.76
Jaro Similarity: 0.8763770830894119
Jaccard Similarity: 0.8461538461538461
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1078, already computed.
Skipping row 1079, already computed.
Skipping row 1080, already computed.
Skipping row 1081, already computed.
Skipping row 1082, already computed.
Movies db locally
1083 movies
Original Query: MATCH (p:Person)-[:ACTED_IN]->(m:Movie) WHERE m.title = "Pearl Harbour" RETURN p.name
Generated Query:
MATCH (p:Person)-[:ACTED_IN]->(m:Movie {title: "Pearl Harbour"})
RETURN p.name
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.6762326627386261
Rouge-L Precision: 1.0
Rouge-L Recall: 0.87
Rouge-L F1-score: 0.93
Jaro Similarity: 0.9386751218706106
Jaccard Similarity: 0.8461538461538461
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1084, already computed.
Skipping row 1085, already computed.
Skipping row 1086, already computed.
Skipping row 1087, already computed.
Skipping row 1088, already computed.
Skipping row 1089, already computed.
Skipping row 1090, already computed.
Skipping row 1091, already computed.
Skipping row 1092, already computed.
Skipping row 1093, already computed.
Skipping row 1094, already computed.
Skipping row 1095, already computed.
Skipping row 1096, already computed.
Skipping row 1097, already computed.
Skipping row 1098, already computed.
Skipping row 1099, already computed.
Skipping row 1100, already computed.
Movies db locally
1101 movies
Original Query: MATCH (actor:Person)-[:ACTED_IN]->(m:Movie) WITH actor, count(m) AS moviesActed ORDER BY moviesActed DESC LIMIT 1 MATCH (actor)-[:ACTED_IN]->(m)<-[:DIRECTED]-(director:Person) WITH director, count(m) AS moviesDirected ORDER BY moviesDirected ASC LIMIT 1 RETURN director.name AS directorName, moviesDirected
Generated Query:
MATCH (actor:Person)-[:ACTED_IN]->(m:Movie)
WITH actor, COUNT(m) AS movieCount
ORDER BY movieCount DESC
LIMIT 1
MATCH (actor)-[:ACTED_IN]->(m:Movie)<-[:DIRECTED]-(director:Person)
WITH director, COUNT(m) AS directedCount
ORDER BY directedCount ASC
LIMIT 1
RETURN director.name, directedCount
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.7369599686031997
Rouge-L Precision: 0.86
Rouge-L Recall: 0.84
Rouge-L F1-score: 0.85
Jaro Similarity: 0.9034742449094555
Jaccard Similarity: 0.7916666666666666
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1102, already computed.
Movies db locally
1103 movies
Original Query: MATCH (m:Movie) WHERE m.tagline CONTAINS 'journey' RETURN m LIMIT 3
Generated Query:
MATCH (m:Movie)
WHERE m.tagline CONTAINS 'journey'
RETURN m.title, m.tagline
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.6406179367095973
Rouge-L Precision: 0.8
Rouge-L Recall: 1.0
Rouge-L F1-score: 0.89
Jaro Similarity: 0.945465032444124
Jaccard Similarity: 0.9090909090909091
Jaccard Output: 0.6666666666666666
Pass@1 Output: False
Skipping row 1104, already computed.
Skipping row 1105, already computed.
Skipping row 1106, already computed.
Skipping row 1107, already computed.
Skipping row 1108, already computed.
Skipping row 1109, already computed.
Skipping row 1110, already computed.
Skipping row 1111, already computed.
Skipping row 1112, already computed.
Skipping row 1113, already computed.
Movies db locally
1114 movies
Original Query: MATCH (p:Person)-[:ACTED_IN]->(m:Movie) WHERE p.born > 1980 WITH p, count(m) AS numMovies WHERE numMovies > 1 RETURN p.name AS actor, numMovies
Generated Query:
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
WHERE p.born > 1980 AND p.born <= 1996
WITH p, COUNT(m) AS movieCount
WHERE movieCount > 1
RETURN p.name, movieCount
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.6331439484087101
Rouge-L Precision: 0.75
Rouge-L Recall: 0.81
Rouge-L F1-score: 0.78
Jaro Similarity: 0.9163295322614783
Jaccard Similarity: 0.7142857142857143
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1115, already computed.
Skipping row 1116, already computed.
Skipping row 1117, already computed.
Skipping row 1118, already computed.
Skipping row 1119, already computed.
Movies db locally
1120 movies
Original Query: MATCH (m:Movie)<-[:REVIEWED {summary: 'An amazing journey'}]-(:Person) RETURN m
Generated Query:
MATCH (:Person)-[r:REVIEWED]->(m:Movie)
WHERE r.summary = 'An amazing journey'
RETURN m.title
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.29867232047430825
Rouge-L Precision: 0.6
Rouge-L Recall: 0.82
Rouge-L F1-score: 0.69
Jaro Similarity: 0.8861492673992674
Jaccard Similarity: 0.7142857142857143
Jaccard Output: 0.3333333333333333
Pass@1 Output: False
Movies db locally
1121 movies
Original Query: MATCH (p:Person)-[r:REVIEWED]->(m:Movie) WHERE r.summary = 'Fun, but a little far fetched' RETURN m.title, r.rating
Generated Query:
MATCH (p:Person)-[r:REVIEWED]->(m:Movie)
WHERE r.summary = 'Fun, but a little far fetched'
RETURN m.title, r.rating
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 1.0
Rouge-L Precision: 1.0
Rouge-L Recall: 1.0
Rouge-L F1-score: 1.0
Jaro Similarity: 1
Jaccard Similarity: 1.0
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1122, already computed.
Skipping row 1123, already computed.
Skipping row 1124, already computed.
Skipping row 1125, already computed.
Skipping row 1126, already computed.
Skipping row 1127, already computed.
Skipping row 1128, already computed.
Skipping row 1129, already computed.
Skipping row 1130, already computed.
Skipping row 1131, already computed.
Skipping row 1132, already computed.
Skipping row 1133, already computed.
Skipping row 1134, already computed.
Movies db locally
1135 movies
Original Query: MATCH (p:Person) WHERE p.born > 1970 AND exists{ (p)-[:ACTED_IN]->(:Movie) } RETURN p.name AS actor, p.born AS year_born
Generated Query:
MATCH (p:Person)-[:ACTED_IN]->(:Movie)
WHERE p.born > 1970
RETURN p.name
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.4850829662827647
Rouge-L Precision: 0.77
Rouge-L Recall: 0.43
Rouge-L F1-score: 0.56
Jaro Similarity: 0.8605555555555556
Jaccard Similarity: 0.6666666666666666
Jaccard Output: 0.45
Pass@1 Output: False
Skipping row 1136, already computed.
Skipping row 1137, already computed.
Skipping row 1138, already computed.
Skipping row 1139, already computed.
Skipping row 1140, already computed.
Skipping row 1141, already computed.
Skipping row 1142, already computed.
Skipping row 1143, already computed.
Skipping row 1144, already computed.
Skipping row 1145, already computed.
Skipping row 1146, already computed.
Skipping row 1147, already computed.
Skipping row 1148, already computed.
Movies db locally
1149 movies
Original Query: MATCH (p:Person)-[:ACTED_IN]->(m:Movie), (p)-[:PRODUCED]->(m) RETURN m.title AS MovieTitle, m.released AS ReleaseYear
Generated Query:
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)<-[:PRODUCED]-(p)
RETURN m.title, p.name
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.5580580927182576
Rouge-L Precision: 0.79
Rouge-L Recall: 0.58
Rouge-L F1-score: 0.67
Jaro Similarity: 0.8934792798551188
Jaccard Similarity: 0.6428571428571429
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1150, already computed.
Skipping row 1151, already computed.
Skipping row 1152, already computed.
Skipping row 1153, already computed.
Skipping row 1154, already computed.
Skipping row 1155, already computed.
Skipping row 1156, already computed.
Skipping row 1157, already computed.
Skipping row 1158, already computed.
Skipping row 1159, already computed.
Skipping row 1160, already computed.
Skipping row 1161, already computed.
Skipping row 1162, already computed.
Movies db locally
1163 movies
Original Query: MATCH (p:Person)-[:ACTED_IN]->(m:Movie) WITH p, count(m) AS movies_count WHERE movies_count > 1 WITH count(p) AS actors_more_than_one_movie MATCH (actor:Person)-[:ACTED_IN]->(:Movie) WITH count(DISTINCT actor) AS total_actors, actors_more_than_one_movie RETURN (actors_more_than_one_movie * 1.0) / total_actors * 100 AS percentage
Generated Query:
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
WITH p, COUNT(m) AS movieCount
WHERE movieCount > 1
WITH COUNT(p) AS actorsWithMultipleMovies
MATCH (p:Person)-[:ACTED_IN]->(:Movie)
WITH COUNT(DISTINCT p) AS totalActors, actorsWithMultipleMovies
RETURN (actorsWithMultipleMovies * 100.0) / totalActors AS percentage
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: None
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: None
BLEU: 0.5747205691589125
Rouge-L Precision: 0.76
Rouge-L Recall: 0.53
Rouge-L F1-score: 0.63
Jaro Similarity: 0.8792428486546133
Jaccard Similarity: 0.6956521739130435
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1164, already computed.
Skipping row 1165, already computed.
Movies db locally
1166 movies
Original Query: MATCH (:Person)-[r:REVIEWED]->(m:Movie) RETURN m.title AS movie, AVG(r.rating) AS average_rating ORDER BY average_rating ASC LIMIT 5
Generated Query:
MATCH (:Person)-[r:REVIEWED]->(m:Movie)
RETURN m.title, AVG(r.rating) AS averageRating
ORDER BY averageRating ASC
LIMIT 5
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.7666674361915814
Rouge-L Precision: 0.9
Rouge-L Recall: 0.75
Rouge-L F1-score: 0.82
Jaro Similarity: 0.9353776061386238
Jaccard Similarity: 0.8421052631578947
Jaccard Output: 1.0
Pass@1 Output: True
Movies db locally
1167 movies

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function: `id`.} {position: line: 1, column: 307, offset: 306} for query: "EXPLAIN MATCH (lilly:Person {name: 'Lilly Wachowski'})-[:DIRECTED]->(lillyMovies:Movie) MATCH (lana:Person {name: 'Lana Wachowski'})-[:DIRECTED]->(lanaMovies:Movie) MATCH (lillyMovies)<-[:ACTED_IN]-(lillyActors:Person) MATCH (lanaMovies)<-[:ACTED_IN]-(lanaActors:Person) WITH lillyActors, lanaActors WHERE id(lillyActors) = id(lanaActors) RETURN DISTINCT lillyActors.name AS actorName"
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function: `id`.} {position: line: 1, column: 325, offset: 324} for query: "EXPLAIN MATCH (lilly:Person {name: 'Lilly Wachowski'})-[:DIRECTED]->(lillyMovies:Movie) MATCH (lana:Person {name: 'Lana Wachowski'})-[:DIRECTED]->(lanaMovies:Movie) MATCH (lillyMovies)<-[:ACTED_IN]-(lillyActors:Person) MATCH (lanaMovies)<-[:ACTED_IN]-(lanaActors:Person) WITH lillyActors, lanaActors WHERE id(lillyActors) = id(lanaActors) RETURN DISTINCT lillyActors.name AS actorName"

Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function: `id`.} {position: line: 1, column: 299, offset: 298} for query: "MATCH (lilly:Person {name: 'Lilly Wachowski'})-[:DIRECTED]->(lillyMovies:Movie) MATCH (lana:Person {name: 'Lana Wachowski'})-[:DIRECTED]->(lanaMovies:Movie) MATCH (lillyMovies)<-[:ACTED_IN]-(lillyActors:Person) MATCH (lanaMovies)<-[:ACTED_IN]-(lanaActors:Person) WITH lillyActors, lanaActors WHERE id(lillyActors) = id(lanaActors) RETURN DISTINCT lillyActors.name AS actorName"
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.FeatureDeprecationWarning} {category: DEPRECATION} {title: This feature is deprecated and will be removed in future versions.} {description: The query used a deprecated function: `id`.} {position: line: 1, column: 317, offset: 316} for query: "MATCH (lilly:Person {name: 'Lilly Wachowski'})-[:DIRECTED]->(lillyMovies:Movie) MATCH (lana:Person {name: 'Lana Wachowski'})-[:DIRECTED]->(lanaMovies:Movie) MATCH (lillyMovies)<-[:ACTED_IN]-(lillyActors:Person) MATCH (lanaMovies)<-[:ACTED_IN]-(lanaActors:Person) WITH lillyActors, lanaActors WHERE id(lillyActors) = id(lanaActors) RETURN DISTINCT lillyActors.name AS actorName"

Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.3126117626348612
Rouge-L Precision: 0.79
Rouge-L Recall: 0.43
Rouge-L F1-score: 0.56
Jaro Similarity: 0.8342231494894821
Jaccard Similarity: 0.35714285714285715
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1204, already computed.
Skipping row 1205, already computed.
Movies db locally

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 33, offset: 32} for query: 'EXPLAIN MATCH (m:Movie) WHERE m.votes IS NOT NULL RETURN m ORDER BY m.votes ASC LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 71, offset: 70} for query: 'EXPLAIN MATCH (m:Movie) WHERE m.votes IS NOT NULL RETURN m ORDER BY m.votes ASC LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 42, offset: 41} for query: 'RETURN exists { MATCH (x:Movie) WHERE (x.votes) IS NOT NULL} AS exists'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 2, column: 35, offset: 43} for query: 'EXPLAIN \nMATCH (m:Movie)\nRETURN m.title, m.votes\nORDER BY m.votes ASC\nLIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 42, offset: 41} for query: 'RETURN exists { MATCH (x:Movie) WHERE (x.votes) IS NOT NULL} AS exists'

1206 movies
Original Query: MATCH (m:Movie) WHERE m.votes IS NOT NULL RETURN m ORDER BY m.votes ASC LIMIT 3
Generated Query:
MATCH (m:Movie)
RETURN m.title, m.votes
ORDER BY m.votes ASC
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 0.0

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 25, offset: 24} for query: 'MATCH (m:Movie) WHERE m.votes IS NOT NULL RETURN m ORDER BY m.votes ASC LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 63, offset: 62} for query: 'MATCH (m:Movie) WHERE m.votes IS NOT NULL RETURN m ORDER BY m.votes ASC LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 2, column: 35, offset: 35} for query: '\nMATCH (m:Movie)\nRETURN m.title, m.votes\nORDER BY m.votes ASC\nLIMIT 3'

Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 0.5
BLEU: 0.5874688340958806
Rouge-L Precision: 0.8
Rouge-L Recall: 0.67
Rouge-L F1-score: 0.73
Jaro Similarity: 0.8811290557253019
Jaccard Similarity: 0.6666666666666666
Jaccard Output: 0.0
Pass@1 Output: False
Skipping row 1207, already computed.
Skipping row 1208, already computed.
Skipping row 1209, already computed.
Skipping row 1210, already computed.
Skipping row 1211, already computed.
Skipping row 1212, already computed.
Skipping row 1213, already computed.
Movies db locally
1214 movies
Original Query: MATCH (m:Movie) WHERE NOT EXISTS { (m)<-[:REVIEWED]-() } RETURN m.title LIMIT 5
Generated Query:
MATCH (m:Movie)
WHERE NOT EXISTS { MATCH (:Person)-[:REVIEWED]->(m) }
RETURN m.title, m.released
ORDER BY m.released DESC
LIMIT 5
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.43756886567968356
Rouge-L Precision: 0.55
Rouge-L Recall: 0.92
Rouge-L F1-score: 0.69
Jaro Similarity: 0.8683874580067189
Jaccard Similarity: 0.6875
Jaccard Output: 0.0
Pass@1 Output: False
Skipping row 1215, already computed.
Skipping row 1216, already computed.
Skipping row 1217, already computed.
Skipping row 1218, already computed.
Skipping row 1219, already computed.
Skipping row 1220, already computed.
Skipping row 1221, already computed.
Skipping row 1222, already computed.
Skipping row 1223, already computed.
Skipping row 1224, already computed.
Skipping row 1225, already computed.
Movies db locally
1226 movies
Original Query: MATCH (m:Movie) WHERE m.tagline IS NOT NULL RETURN m.title, m.tagline ORDER BY m.tagline DESC LIMIT 3
Generated Query: ```cypher
MATCH (m:Movie)
RETURN m.title, m.tagline, COUNT(DISTINCT m.tagline) AS taglineCount
ORDER BY taglineCount DESC
LIMIT 3
```
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: False
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.4516250031620747
Rouge-L Precision: 0.62
Rouge-L Recall: 0.62
Rouge-L F1-score: 0.62
Jaro Similarity: 0.7244564112985166
Jaccard Similarity: 0.5238095238095238
Not syntax correct, skipped pass and jaccard output
Skipping row 1227, already computed.
Skipping row 1228, already computed.
Skipping row 1229, already computed.
Skipping row 1230, already computed.
Skipping row 1231, already computed.
Skipping row 1232, already computed.
Skipping row 1233, already computed.
Skipping row 1234, already computed.
Skipping row 1235, already computed.
Skipping row 1236, already computed.
Skipping row 1237, already computed.
Skipping row 1238, already computed.
Skipping row 1239, already computed.
Skipping row 1240, already computed.
Movies db locally
1241 movies
Original Query: MATCH (p:Person)-[:ACTED_IN]->(m:Movie) WHERE m.tagline CONTAINS 'journey' WITH p, count(m) AS movieCount ORDER BY movieCount DESC LIMIT 3 RETURN p.name
Generated Query:
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
WHERE m.tagline CONTAINS 'journey'
RETURN p.name, COUNT(m) AS movieCount
ORDER BY movieCount DESC
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.8292356276487494
Rouge-L Precision: 0.92
Rouge-L Recall: 0.85
Rouge-L F1-score: 0.88
Jaro Similarity: 0.9491428571428571
Jaccard Similarity: 0.9523809523809523
Jaccard Output: 0.5
Pass@1 Output: False
Skipping row 1242, already computed.
Skipping row 1243, already computed.
Skipping row 1244, already computed.
Movies db locally
1245 movies
Original Query: MATCH (p:Person)-[r:ACTED_IN]->(m:Movie) WITH p, count(DISTINCT r.roles) AS distinctRoles ORDER BY distinctRoles DESC LIMIT 3 RETURN p.name, distinctRoles
Generated Query:
MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
WITH p, size(apoc.coll.toSet(collect(r.roles))) AS distinctRolesCount
RETURN p.name, distinctRolesCount
ORDER BY distinctRolesCount DESC
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: False
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.5629065548114563
Rouge-L Precision: 0.62
Rouge-L Recall: 0.69
Rouge-L F1-score: 0.65
Jaro Similarity: 0.8892400817319617
Jaccard Similarity: 0.6538461538461539
Not syntax correct, skipped pass and jaccard output
Skipping row 1246, already computed.
Skipping row 1247, already computed.
Skipping row 1248, already computed.
Skipping row 1249, already computed.
Skipping row 1250, already computed.
Skipping row 1251, already computed.
Skipping row 1252, already computed.
Skipping row 1253, already computed.
Skipping row 1254, already computed.
Skipping row 1255, already computed.
Movies db locally
1256 movies
Original Query: MATCH (m:Movie) RETURN m.title, size(m.title) AS length ORDER BY length DESC LIMIT 1
Generated Query: ```cypher
MATCH (m:Movie)
RETURN m.title
ORDER BY length(m.title) DESC
LIMIT 1
```
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: False
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.6103779413213909
Rouge-L Precision: 0.8
Rouge-L Recall: 0.71
Rouge-L F1-score: 0.75
Jaro Similarity: 0.7656209021767637
Jaccard Similarity: 0.7333333333333333
Not syntax correct, skipped pass and jaccard output
Skipping row 1257, already computed.
Skipping row 1258, already computed.
Skipping row 1259, already computed.
Skipping row 1260, already computed.
Skipping row 1261, already computed.
Skipping row 1262, already computed.
Skipping row 1263, already computed.
Skipping row 1264, already computed.
Skipping row 1265, already computed.
Skipping row 1266, already computed.
Movies db locally
1267 movies
Original Query: MATCH (m:Movie {title: "V for Vendetta"})<-[:DIRECTED]-(p:Person) RETURN p.name
Generated Query: MATCH (p:Person)-[:DIRECTED]->(m:Movie {title: "V for Vendetta"})
RETURN p.name
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.7512149931115434
Rouge-L Precision: 0.77
Rouge-L Recall: 0.77
Rouge-L F1-score: 0.77
Jaro Similarity: 0.9080489101541733
Jaccard Similarity: 1.0
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1268, already computed.
Skipping row 1269, already computed.
Skipping row 1270, already computed.
Skipping row 1271, already computed.
Skipping row 1272, already computed.
Skipping row 1273, already computed.
Skipping row 1274, already computed.
Skipping row 1275, already computed.
Skipping row 1276, already computed.
Skipping row 1277, already computed.
Skipping row 1278, already computed.
Skipping row 1279, already computed.
Skipping row 1280, already computed.
Skipping row 1281, already computed.
Skipping row 1282, already computed.
Skipping row 1283, already computed.
Skipping row 1284, already computed.
Skipping row 1285, already computed.
Skipping row 1286, already computed.
Movies db locally

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 39, offset: 38} for query: 'EXPLAIN MATCH (m:Movie) WITH m, avg(m.votes) AS average_votes MATCH (p:Person)-[:DIRECTED]->(m) WITH p, average_votes ORDER BY average_votes DESC RETURN p.name AS director_name, avg(average_votes) AS average_movie_votes LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 42, offset: 41} for query: 'RETURN exists { MATCH (x:Movie) WHERE (x.votes) IS NOT NULL} AS exists'

1287 movies
Original Query: MATCH (m:Movie) WITH m, avg(m.votes) AS average_votes MATCH (p:Person)-[:DIRECTED]->(m) WITH p, average_votes ORDER BY average_votes DESC RETURN p.name AS director_name, avg(average_votes) AS average_movie_votes LIMIT 3
Generated Query:
MATCH (d:Person)-[:DIRECTED]->(m:Movie)
WITH d, avg(m.votes) AS avgVotes
ORDER BY avgVotes DESC
LIMIT 3
RETURN d.name, avgVotes

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 3, column: 15, offset: 63} for query: 'EXPLAIN \nMATCH (d:Person)-[:DIRECTED]->(m:Movie)\nWITH d, avg(m.votes) AS avgVotes\nORDER BY avgVotes DESC\nLIMIT 3\nRETURN d.name, avgVotes'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 42, offset: 41} for query: 'RETURN exists { MATCH (x:Movie) WHERE (x.votes) IS NOT NULL} AS exists'

Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 0.5
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 0.5
BLEU: 0.4026569660299501
Rouge-L Precision: 0.57
Rouge-L Recall: 0.33
Rouge-L F1-score: 0.41
Jaro Similarity: 0.8216222918621277
Jaccard Similarity: 0.7272727272727273

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 31, offset: 30} for query: 'MATCH (m:Movie) WITH m, avg(m.votes) AS average_votes MATCH (p:Person)-[:DIRECTED]->(m) WITH p, average_votes ORDER BY average_votes DESC RETURN p.name AS director_name, avg(average_votes) AS average_movie_votes LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.AggregationSkippedNull} {category: UNRECOGNIZED} {title: The query contains an aggregation function that skips null values.} {description: null value eliminated in set function.} {position: None} for query: 'MATCH (m:Movie) WITH m, avg(m.votes) AS average_votes MATCH (p:Person)-[:DIRECTED]->(m) WITH p, average_votes ORDER BY average_votes DESC RETURN p.name AS director_name, avg(average_votes) AS average_movie_votes LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 3, column: 15, offset: 55} for query: '\nMATCH (d:Person)-[:DIRECTED]->(m:Movie)\nWITH d, avg(m.votes) AS avgVotes\nORDER BY avgVotes DESC\nLIMIT 3\nRETURN d.name, avgVotes'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.AggregationSkippedNull} {category: UNRECOGNIZED} {title: The query contains an aggregation function that skips null values.} {description: null value eliminated in set function.} {position: None} for query: '\nMATCH (d:Person)-[:DIRECTED]->(m:Movie)\nWITH d, avg(m.votes) AS avgVotes\nORDER BY avgVotes DESC\nLIMIT 3\nRETURN d.name, avgVotes'

Jaccard Output: 0.3333333333333333
Pass@1 Output: False
Skipping row 1288, already computed.
Skipping row 1289, already computed.
Movies db locally
1290 movies
Original Query: MATCH (m:Movie) WHERE m.title CONTAINS "Mail" RETURN m.title
Generated Query:
MATCH (m:Movie) WHERE m.title CONTAINS "Mail" RETURN m.title AS movieTitle
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.878187983790713
Rouge-L Precision: 0.85
Rouge-L Recall: 1.0
Rouge-L F1-score: 0.92
Jaro Similarity: 0.9658536585365853
Jaccard Similarity: 0.8
Jaccard Output: 1.0
Pass@1 Output: True
Movies db locally

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 33, offset: 32} for query: 'EXPLAIN MATCH (m:Movie) WHERE m.votes < 100 RETURN m.title ORDER BY m.votes LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 71, offset: 70} for query: 'EXPLAIN MATCH (m:Movie) WHERE m.votes < 100 RETURN m.title ORDER BY m.votes LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 42, offset: 41} for query: 'RETURN exists { MATCH (x:Movie) WHERE (x.votes) IS NOT NULL} AS exists'

1291 movies
Original Query: MATCH (m:Movie) WHERE m.votes < 100 RETURN m.title ORDER BY m.votes LIMIT 3
Generated Query:
MATCH (m:Movie)
WHERE m.votes < 100
RETURN m.title, m.votes
ORDER BY m.votes
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 0.5

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 3, column: 9, offset: 33} for query: 'EXPLAIN \nMATCH (m:Movie)\nWHERE m.votes < 100\nRETURN m.title, m.votes\nORDER BY m.votes\nLIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 4, column: 19, offset: 63} for query: 'EXPLAIN \nMATCH (m:Movie)\nWHERE m.votes < 100\nRETURN m.title, m.votes\nORDER BY m.votes\nLIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 42, offset: 41} for query: 'RETURN exists { MATCH (x:Movie) WHERE (x.votes) IS NOT NULL} AS exists'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 25, offset: 24} for query: 'MATCH (m:Movie) WHERE m.votes < 100 RETURN m.title ORDER BY m.votes LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 63, offset: 62} for query: 'MATCH (m:Movie) WHERE m.votes < 100 RETURN m.title ORDER BY m.votes LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 3, column: 9, offset: 25} for query: '\nMATCH (m:Movie)\nWHERE m.votes < 100\nRETURN m.title, m.votes\nORDER BY m.votes\nLIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 4, column: 19, offset: 55} for query: '\nMATCH (m:Movie)\nWHERE m.votes < 100\nRETURN m.title, m.votes\nORDER BY m.votes\nLIMIT 3'

Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 0.5
BLEU: 0.7801270245332924
Rouge-L Precision: 0.89
Rouge-L Recall: 1.0
Rouge-L F1-score: 0.94
Jaro Similarity: 0.9470224378411158
Jaccard Similarity: 1.0
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1292, already computed.
Skipping row 1293, already computed.
Skipping row 1294, already computed.
Movies db locally
1295 movies
Original Query: MATCH (p:Person)-[:ACTED_IN]->(m:Movie) WHERE m.released >= 1990 AND m.released < 2000 RETURN p.name LIMIT 3
Generated Query:
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
WHERE m.released >= 1990 AND m.released < 2000
RETURN p
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.9054493691797888
Rouge-L Precision: 1.0
Rouge-L Recall: 0.95
Rouge-L F1-score: 0.97
Jaro Similarity: 0.9843527204502814
Jaccard Similarity: 0.9375
Jaccard Output: 0.5
Pass@1 Output: False
Skipping row 1296, already computed.
Movies db locally

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 57, offset: 56} for query: 'EXPLAIN MATCH (p:Person)-[:PRODUCED]->(m:Movie) WHERE m.votes > 500 RETURN p.name LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 42, offset: 41} for query: 'RETURN exists { MATCH (x:Movie) WHERE (x.votes) IS NOT NULL} AS exists'

1297 movies
Original Query: MATCH (p:Person)-[:PRODUCED]->(m:Movie) WHERE m.votes > 500 RETURN p.name LIMIT 3
Generated Query:
MATCH (p:Person)-[:PRODUCED]->(m:Movie)
WHERE m.votes > 500
RETURN p.name
ORDER BY m.released
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 0.5

WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 3, column: 9, offset: 57} for query: 'EXPLAIN \nMATCH (p:Person)-[:PRODUCED]->(m:Movie)\nWHERE m.votes > 500\nRETURN p.name\nORDER BY m.released\nLIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 42, offset: 41} for query: 'RETURN exists { MATCH (x:Movie) WHERE (x.votes) IS NOT NULL} AS exists'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 1, column: 49, offset: 48} for query: 'MATCH (p:Person)-[:PRODUCED]->(m:Movie) WHERE m.votes > 500 RETURN p.name LIMIT 3'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: votes)} {position: line: 3, column: 9, offset: 49} for query: '\nMATCH (p:Person)-[:PRODUCED]->(m:Movie)\nWHERE m.votes > 500\nRETURN p.name\nORDER BY m.released\nLIMIT 3'

Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 0.6666666666666666
BLEU: 0.8060316973271656
Rouge-L Precision: 0.79
Rouge-L Recall: 1.0
Rouge-L F1-score: 0.88
Jaro Similarity: 0.9579344262295082
Jaccard Similarity: 0.8125
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1298, already computed.
Skipping row 1299, already computed.
Skipping row 1300, already computed.
Skipping row 1301, already computed.
Movies db locally
1302 movies
Original Query: MATCH (m:Movie)<-[ai:ACTED_IN]-(p:Person) RETURN m.title AS movie, collect(p.name) AS actors, size(ai.roles) AS numRoles ORDER BY numRoles DESC LIMIT 5
Generated Query: ```
MATCH (p:Person)-[r:ACTED_IN]->(m:Movie)
WITH m, count(r.roles) AS roleCount, collect(p.name) AS actors
ORDER BY roleCount DESC
LIMIT 5
RETURN m.title AS movieTitle, roleCount, actors
```
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: False
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.4327466495895045
Rouge-L Precision: 0.45
Rouge-L Recall: 0.52
Rouge-L F1-score: 0.48
Jaro Similarity: 0.7557076934229278
Jaccard Similarity: 0.6428571428571429
Not syntax correct, skipped pass and jaccard output
Skipping row 1303, already computed.
Skipping row 1304, already computed.
Skipping row 1305, already computed.
Skipping row 1306, already computed.
Skipping row 1307, already computed.
Skipping row 1308, already computed.
Movies db locally
1309 movies
Original Query: MATCH (p:Person {name: "Keanu Reeves"})-[:FOLLOWS]->(followed:Person) WHERE followed.born >= 1960 AND followed.born < 1970 RETURN followed ORDER BY followed.born LIMIT 3
Generated Query:
MATCH (keanu:Person {name: "Keanu Reeves"})-[:FOLLOWS]->(p:Person)
WHERE p.born >= 1960 AND p.born < 1970
RETURN p.name, p.born
ORDER BY p.born
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.5988059642324198
Rouge-L Precision: 0.68
Rouge-L Recall: 0.76
Rouge-L F1-score: 0.72
Jaro Similarity: 0.8461643585642252
Jaccard Similarity: 0.9
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1310, already computed.
Movies db locally
1311 movies
Original Query: MATCH (m:Movie)<-[:ACTED_IN]-(p:Person) WITH m, count(p) AS actorCount WHERE actorCount > 3 RETURN m.title AS MovieTitle, actorCount
Generated Query:
MATCH (m:Movie)<-[:ACTED_IN]-(p:Person)
WITH m, COUNT(p) AS actorCount
WHERE actorCount > 3
RETURN m.title, actorCount
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.8395114512542857
Rouge-L Precision: 1.0
Rouge-L Recall: 0.91
Rouge-L F1-score: 0.95
Jaro Similarity: 0.9732467532467532
Jaccard Similarity: 0.9333333333333333
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1312, already computed.
Skipping row 1313, already computed.
Skipping row 1314, already computed.
Movies db locally
1315 movies
Original Query: MATCH (p:Person)-[r:REVIEWED]->(m:Movie) WITH p, r, m ORDER BY r.rating ASC LIMIT 1 RETURN p.name AS reviewer, m.title AS movie, r.rating AS rating
Generated Query:
MATCH (p:Person)-[r:REVIEWED]->(m:Movie)
WITH p, r, m
ORDER BY r.rating ASC
LIMIT 1
RETURN p.name, m.title, r.rating
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.8082793786615993
Rouge-L Precision: 1.0
Rouge-L Recall: 0.81
Rouge-L F1-score: 0.89
Jaro Similarity: 0.9520714285714286
Jaccard Similarity: 0.85
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1316, already computed.
Skipping row 1317, already computed.
Skipping row 1318, already computed.
Skipping row 1319, already computed.
Skipping row 1320, already computed.
Skipping row 1321, already computed.
Skipping row 1322, already computed.
Skipping row 1323, already computed.
Skipping row 1324, already computed.
Skipping row 1325, already computed.
Skipping row 1326, already computed.
Movies db locally
1327 movies
Original Query: MATCH (p:Person)-[:ACTED_IN]->(m:Movie) WHERE m.released = 2012 RETURN p.name LIMIT 3
Generated Query:
MATCH (p:Person)-[:ACTED_IN]->(m:Movie {released: 2012})
RETURN p.name
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.7099394630852857
Rouge-L Precision: 1.0
Rouge-L Recall: 0.88
Rouge-L F1-score: 0.93
Jaro Similarity: 0.9344645955548211
Jaccard Similarity: 0.8571428571428571
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1328, already computed.
Skipping row 1329, already computed.
Movies db locally
1330 movies
Original Query: MATCH (p:Person)<-[:FOLLOWS]-(follower:Person) WITH p, COUNT(follower) AS followerCount ORDER BY followerCount DESC LIMIT 5 RETURN p.name AS personName, followerCount
Generated Query:
MATCH (p:Person)<-[:FOLLOWS]-(follower:Person)
RETURN p.name, COUNT(follower) AS followersCount
ORDER BY followersCount DESC
LIMIT 5
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.624145576865935
Rouge-L Precision: 0.79
Rouge-L Recall: 0.62
Rouge-L F1-score: 0.7
Jaro Similarity: 0.905131780222354
Jaccard Similarity: 0.7777777777777778
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1331, already computed.
Skipping row 1332, already computed.
Skipping row 1333, already computed.
Skipping row 1334, already computed.
Skipping row 1335, already computed.
Skipping row 1336, already computed.
Skipping row 1337, already computed.
Skipping row 1338, already computed.
Movies db locally
1339 movies
Original Query: MATCH (p:Person)-[:DIRECTED]->(m:Movie) RETURN p.name AS director, m.title AS movie, m.released - p.born AS age_at_release ORDER BY age_at_release ASC LIMIT 1
Generated Query:
MATCH (p:Person)-[:DIRECTED]->(m:Movie)
RETURN p.name, m.title, (m.released - p.born) AS age_at_release
ORDER BY age_at_release ASC
LIMIT 1
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.7802943278540929
Rouge-L Precision: 1.0
Rouge-L Recall: 0.87
Rouge-L F1-score: 0.93
Jaro Similarity: 0.9256058219282568
Jaccard Similarity: 0.9
Jaccard Output: 1.0
Pass@1 Output: True
Movies db locally
1340 movies
Original Query: MATCH (p:Person)-[r:REVIEWED]->(m:Movie) WITH p, count(m) AS movies_reviewed WHERE movies_reviewed > 1 RETURN p LIMIT 3
Generated Query:
MATCH (p:Person)-[:REVIEWED]->(m:Movie)
WITH p, COUNT(m) AS reviewCount
WHERE reviewCount > 1
RETURN p.name
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: None
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.647175502660626
Rouge-L Precision: 0.85
Rouge-L Recall: 0.77
Rouge-L F1-score: 0.81
Jaro Similarity: 0.89302827187965
Jaccard Similarity: 0.7777777777777778
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1341, already computed.
Skipping row 1342, already computed.
Skipping row 1343, already computed.
Skipping row 1344, already computed.
Skipping row 1345, already computed.
Skipping row 1346, already computed.
Skipping row 1347, already computed.
Skipping row 1348, already computed.
Skipping row 1349, already computed.
Skipping row 1350, already computed.
Skipping row 1351, already computed.
Skipping row 1352, already computed.
Skipping row 1353, already computed.
Skipping row 1354, already computed.
Skipping row 1355, already computed.
Skipping row 1356, already computed.
Skipping row 1357, already computed.
Skipping row 1358, already computed.
Skipping row 1359, already computed.
Skipping row 1360, already computed.
Skipping row 1361, already computed.
Skipping row 1362, already computed.
Skipping row 1363, already computed.
Skipping row 1364, already computed.
Skipping row 1365, already computed.
Skipping row 1366, already computed.
Skipping row 1367, already computed.
Skipping row 1368, already computed.
Skipping row 1369, already computed.
Skipping row 1370, already computed.
Skipping row 1371, already computed.
Skipping row 1372, already computed.
Skipping row 1373, already computed.
Skipping row 1374, already computed.
Skipping row 1375, already computed.
Movies db locally
1376 movies
Original Query: MATCH (m:Movie)<-[r:REVIEWED]-(p:Person) WHERE r.summary CONTAINS 'coolest' AND m.released > 2000 RETURN count(m)
Generated Query: MATCH (m:Movie)<-[r:REVIEWED]-(p:Person)
WHERE m.released > 2000 AND r.summary CONTAINS "coolest"
RETURN count(DISTINCT m) AS numberOfMovies
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.696130448219275
Rouge-L Precision: 0.68
Rouge-L Recall: 0.79
Rouge-L F1-score: 0.73
Jaro Similarity: 0.9241625686077013
Jaccard Similarity: 0.75
Jaccard Output: 1.0
Pass@1 Output: True
Movies db locally
1377 movies
Original Query: MATCH (p:Person)-[:ACTED_IN]->(m:Movie) RETURN p.name, COUNT(m) AS movies_count ORDER BY movies_count DESC LIMIT 10
Generated Query:
MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
RETURN p.name, COUNT(m) AS movieCount
ORDER BY movieCount DESC
LIMIT 10
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.8492919530422433
Rouge-L Precision: 0.9
Rouge-L Recall: 0.82
Rouge-L F1-score: 0.86
Jaro Similarity: 0.9666077060194708
Jaccard Similarity: 0.8823529411764706
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1378, already computed.
Movies db locally
1379 movies
Original Query: MATCH (m:Movie {released: 2003})<-[r:REVIEWED]-() WITH avg(r.rating) AS averageRating RETURN averageRating
Generated Query: MATCH (:Person)-[r:REVIEWED]->(m:Movie)
WHERE m.released = 2003
RETURN avg(r.rating) AS average_rating
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.41047223861420173
Rouge-L Precision: 0.53
Rouge-L Recall: 0.6
Rouge-L F1-score: 0.56
Jaro Similarity: 0.8745561283915361
Jaccard Similarity: 0.6470588235294118
Jaccard Output: 1.0
Pass@1 Output: True
Skipping row 1380, already computed.
Skipping row 1381, already computed.
Skipping row 1382, already computed.
Skipping row 1383, already computed.
Skipping row 1384, already computed.
Skipping row 1385, already computed.
Skipping row 1386, already computed.
Skipping row 1387, already computed.
Skipping row 1388, already computed.
Skipping row 1389, already computed.
Skipping row 1390, already computed.
Skipping row 1391, already computed.
Skipping row 1392, already computed.
Skipping row 1393, already computed.
Skipping row 1394, already computed.
Skipping row 1395, already computed.
Skipping row 1396, already computed.
Skipping row 1397, already computed.
Skipping row 1398, already computed.
Skipping row 1399, already computed.
Skipping row 1400, already computed.

In [5]:
df = pd.read_pickle('BenchmarkDataset2025/gpt_4o/gpt_4o_eleftheria.pkl')
# Example: assume your DataFrame is called df and column is "tokens"
# Show all rows after 1400 where 'tokens' is NaN
nan_rows = df.loc[(df.index >700) & (df.index <=1400)]
# & (df["Pass@1 Output"].isna()) & (df["Syntax Valid"]==True)
nan_rows.isna().sum()

question                         0
schema                           0
cypher                           0
data_source                      0
instance_id                      0
database_reference_alias         0
url                              0
database_name                    0
username                         0
password                         0
generated_cypher                 1
answer                           1
path                             1
output                           1
eval_time_s                      1
total_tokens                     1
completion_tokens                1
prompt_tokens                    1
Original Syntax Valid            0
Original Syntax Metadata         0
Original Schema Valid            0
Original Schema Metadata         0
Original Properties Valid       14
Original Properties Metadata     0
Syntax Valid                     0
Syntax Metadata                  0
Schema Valid                     0
Schema Metadata                  0
Properties Valid                 7
Properties Metadata              0
Pass@1 Output                    9
Jaccard Output                   9
BLEU                             0
Rouge-L Precision                0
Rouge-L Recall                   0
Rouge-L F1-score                 0
Jaro Similarity                  0
Jaccard Similarity               0
dtype: int64

In [8]:
df = pd.read_pickle('BenchmarkDataset2025/gpt_4o/gpt_4o_eleftheria.pkl')
# Example: assume your DataFrame is called df and column is "tokens"
# Show all rows after 1400 where 'tokens' is NaN
nan_rows = df.loc[(df.index >700) & (df.index <=1400) & (df["Pass@1 Output"].isna())]

# nan_rows = df.loc[(df.index > 1400) & (df["Pass@1 Output"].isna())]
# & (df["Syntax Valid"]==True)
nan_rows[['Syntax Valid']]

     Syntax Valid
718           0.0
738           0.0
1122          0.0
1171          0.0
1226        False
1233          0.0
1245        False
1256        False
1302        False

In [10]:
nan_rows[['question','database_name','generated_cypher','cypher',
       #    'Original Syntax Valid', 'Original Syntax Metadata',
       # 'Original Schema Valid', 'Original Schema Metadata',
       # 'Original Properties Valid', 'Original Properties Metadata',
       'Syntax Valid', 'Syntax Metadata', 'Schema Valid', 'Schema Metadata',
       'Properties Valid', 'Properties Metadata', 'Pass@1 Output',
       'Jaccard Output', 'BLEU', 'Rouge-L Precision', 'Rouge-L Recall',
       'Rouge-L F1-score', 'Jaro Similarity', 'Jaccard Similarity']]

,question,database_name,generated_cypher,cypher,Syntax Valid,Syntax Metadata,Schema Valid,Schema Metadata,Properties Valid,Properties Metadata,Pass@1 Output,Jaccard Output,BLEU,Rouge-L Precision,Rouge-L Recall,Rouge-L F1-score,Jaro Similarity,Jaccard Similarity
1603,List the top 5 suppliers based on the number o...,northwind,MATCH (s:Supplier)-[:SUPPLIES]->(:Product)<-[:...,MATCH (s:Supplier)-[:SUPPLIES]->(p:Product)<-[...,False,[{'code': 'Neo.ClientError.Statement.SyntaxErr...,1.0,[],1.0,[],None,None,0.56611,0.81,0.66,0.72,0.889328,0.703704
1733,What is the total revenue generated by orders ...,northwind,\nMATCH (c:Customer)-[:PURCHASED]->(o:Order)-[...,MATCH (c:Customer)-[:PURCHASED]->(o:Order)-[re...,False,[{'code': 'Neo.ClientError.Statement.SyntaxErr...,1.0,[],1.0,[],None,None,0.553933,0.68,0.64,0.66,0.869963,0.689655
1872,Which services listen to port 443 and are inst...,network,MATCH (s:Service)-[:LISTENS]->(p:Port {port: 4...,MATCH (s:Service {name: 'java'})-[:LISTENS]->(...,False,[{'code': 'Neo.ClientError.Statement.SyntaxErr...,1.0,[],1.0,[],None,None,0.589041,0.69,0.75,0.72,0.833459,0.769231
1877,"""Which is the best rated movie""",movies,\nMATCH (m:Movie)<-[:REVIEWED]-(p:Person)\nRET...,MATCH (:Person)-[r:REVIEWED]->(m:Movie)\nRETUR...,False,[{'code': 'Neo.ClientError.Statement.SyntaxErr...,1.0,[],1.0,[],None,None,0.348612,0.7,0.67,0.68,0.882163,0.789474
1992,What are the names of the top 3 categories bas...,northwind,```\nMATCH (s:Supplier)-[:SUPPLIES]->(p:Produc...,MATCH (s:Supplier)-[:SUPPLIES]->(p:Product)-[:...,False,[{'code': 'Neo.ClientError.Statement.SyntaxErr...,1.0,[],1.0,[],None,None,0.839696,0.93,0.87,0.9,0.794187,0.913043
1995,Identify the top 5 hashtags used in tweets tha...,twitter,NaN,MATCH (me:Me {screen_name: 'neo4j'})-[:POSTS]-...,False,[],0,[],0,[],None,None,0,0,0,0,0,0
2045,What are the top 3 software names that depend ...,network,NaN,MATCH (s:Software)-[:DEPENDS_ON]->(:Applicatio...,False,[],0,[],0,[],None,None,0,0,0,0,0,0
2097,What is the total `amount` of filings where th...,fincen,\nMATCH (c:Country)<-[:COUNTRY]-(e:Entity)<-[:...,MATCH (c:Country)<-[:COUNTRY]-(:Entity)\nWITH ...,False,[{'code': 'Neo.ClientError.Statement.SyntaxErr...,1.0,[],1.0,[],None,None,0.548486,0.72,0.76,0.74,0.889456,0.833333
2127,How can I create multiple Movie nodes from a p...,recommendations,\nUNWIND $movies AS movieData\nCREATE (m:Movie...,UNWIND $movieList AS movieData\nCREATE (m:Movi...,False,[{'code': 'Neo.ClientNotification.Statement.Pa...,1.0,[],1.0,[],None,None,0.190258,0.2,0.61,0.3,0.597762,0.36

In [5]:
2/19

0.10526315789473684

### For usage metrics

In [ ]:
# # SustainDataset
# dataset = 'BenchmarkDataset2025'
# model_name ='gpt_4o' #'qwen2_5_72b' #'qwen2_5_Coder_32b' #'llama3_2_3b'
# # path = f'../Outputs_Evaluation/{dataset}/{model_name}/{model_name}.xlsx'
# path = f'../Outputs_Evaluation/{dataset}/{model_name}/{model_name}_usage.xlsx'

# # Read the model results
# model_df = pd.read_excel(path)

# # Calculate the scores
# df = calculate_scores(model_name,dataset,model_df, save = False)
# #save

# df.to_pickle(f'../Outputs_Evaluation/{dataset}/{model_name}/{model_name}_usage.pkl')
# df.to_excel(path, index=False)

  0%|          | 0/2124 [00:00<?, ?it/s]

0 northwind
Original Query: MATCH (s:Supplier)-[:SUPPLIES]->(p:Product) WITH s, avg(p.unitPrice) AS avgUnitPrice ORDER BY avgUnitPrice DESC LIMIT 5 RETURN s.companyName AS Supplier, avgUnitPrice AS AverageUnitPrice
Generated Query: MATCH (s:Supplier)-[:SUPPLIES]->(p:Product)
RETURN s.companyName, AVG(p.unitPrice) AS averageUnitPrice
ORDER BY averageUnitPrice DESC
LIMIT 5
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.5659687954299661
Rouge-L Precision: 0.8
Rouge-L Recall: 0.59
Rouge-L F1-score: 0.68
Jaro Similarity: 0.9061904761904762
Jaccard Similarity: 0.8
Pass@1 Output: True
Jaccard Output: 1.0
1 neoflix
Original Query: MATCH (m:Movie)-[:IN_GENRE]->(g:Genre) WITH g, avg(m.revenue) AS avg_revenue ORDER BY avg_revenue ASC LIMIT 3 RETURN g.name AS genre, avg_revenue
Generated Query:
MATCH (m:Movie)-[:IN_GENRE]->(g:Genre)
WITH g, avg(m.revenue) AS avg_revenue
ORDER BY avg_revenue ASC
RETURN g.name, avg_revenue
LIMIT 3
Original Syntax Valid: True
Original Schema Valid: 1.0
Original Properties Valid: 1.0
Syntax Valid: True
Schema Valid: 1.0
Properties Valid: 1.0
BLEU: 0.8475517548728019
Rouge-L Precision: 0.93
Rouge-L Recall: 0.86
Rouge-L F1-score: 0.89
Jaro Similarity: 0.9668491124260354
Jaccard Similarity: 0.9473684210526315

KeyboardInterrupt: